### ISSUE TITLE
catchUndef versus empty set

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#387]
Copying from #382 where this seems to have been lost in the noise:

```
find S : set of int(1..2) such that S = {1} intersect {2}
find t : int(0..2) such that t = catchUndef(max(S),0)
```

has no solutions, while

```
letting S be {1} intersect {2}
find t : int(0..2) such that t = catchUndef(max(S),0)
```

has solution 0.

I don't believe these should differ (they should both have solution 0).

**Comment by ozgurakgun** [comment]
Since catchUndef is a recent addition and it is mainly intended to be used in the output I had never tested this. You are right, there is a discrepancy here. It is because for the 2nd example SR handles the undefinedness, and for the 1st example Conjure does (wrongly!).

I'll look into a fix - shouldn't be too hard.

**Comment by ozgurakgun** [comment]
By the way there is another case we should test. `max(T)` where T is an empty set of bools is also undefined. but in this case the equality is not undefined, the value of `max(T)` is false.

Relational semantics...

I'll add test cases for that too.

**Comment by ozgurakgun** [comment]
See https://bitbucket.org/stacs_cp/savilerow/issues/183

**Comment by pwn1** [comment]
You need to keep a hash of every eprime file ever produced by Conjure, and only accept catchUndef in those files. That way Andras can't use it.
