### ISSUE TITLE
Print progress when solving

### ISSUE THREAD

**Issue by Revilotom** [conjure-cp/conjure#418]
Just a thought.

It might be nice to know what stage the task has reached, like:

Conjure modelling started..
Savilerow started..
Minion started..

**Comment by SaadAttieh** [comment]
Agreed, not sure if this would be too much but it would also be good to see some of SRs messages passed through like domain filtering. In the long term, in order to better support local search, a mode where the pipeline outputs info on the solver such as current best objective, time taken, etc. would be useful. But perhaps as a first step, just info on the different stages. 

Regards, 
Saad

**Comment by ozgurakgun** [comment]
This is coming.

**Comment by ozgurakgun** [comment]
Is this what you were after @Revilotom?

**Comment by Revilotom** [comment]
Yes thank you!
