### ISSUE TITLE
Incorrect refinement of size of set literal containing decision variables 

### ISSUE THREAD

**Issue by MHHenriksen** [conjure-cp/conjure#511]
It's as simple as `find a,b,c:int(1..3) such that |{a,b,c}|=3` which gets refined to
```
language ESSENCE' 1.0

find a: int(1..3)
find b: int(1..3)
find c: int(1..3)
branching on [a, b, c]
such that true
```

Command used: `conjure solve --log-level=LogWarn -ac --solutions-in-one-file --number-of-solutions=10 --validate-solutions --solver=chuffed --limit-time=900 --log-rule-successes --verbose-trail --rewrites-trail --log-choices $files`

...why I'm doing that, you ask? Well, to work around problems and issues with more obvious way to formulate the same criteria. Check out https://replit.com/@SuperMikal/Conjure-and-Essence-20220507 if you want to have a look (please excuse the mess :P). You can also get an instant repro by forking it and running `bash main.sh issue1.essence` in the console.

**Comment by ozgurakgun** [comment]
That's emberrasing, but thankfully easy to fix!

**Comment by ozgurakgun** [comment]
By the way the new output has `such that allDiff([a, b, c; int(1..3)])` in it. And thanks for reporting!

**Comment by stylpe** [comment]
Thanks, that was super quick!

May I ask for a bit of advice? I've finally stumbled my way to the solution I was looking for, but had a lot of trouble getting there. I have a long list of potential issues that could use some triaging, but I don't want to spam you and take too much of your time either, because I'm not always sure if I've just misunderstood something or if it's actually a bug or even a feature request. 

So the question is how would you like to receive this? I could make individual issues, or one big summary issue that can be filtered first and then making detailed issues for anything that survives, or I can write a summary in the replit itself with some examples, and let you pick and choose from there, or some combination of that, or something completely different...
